### ISSUE TITLE
Updating CoreRoller? 

### ISSUE THREAD

**Issue by clemenko** [coreroller/coreroller#11]
What is the prefered method for updating CoreRoller's database? We work on an air gapped network and would love to be able to move updates to the private network. Assuming we can snapshot the db and move it and the files across. Does this make sense?

**Comment by tegioz** [comment]
Hi @clemenko 

Unfortunately there isn't a nice way as of today to add new CoreOS packages / keep up to date the channels when the box running rollerd (syncer component) doesn't have access to the Internet and the solution you propose is the only way to go.

After an initial full dump/restore of the db (to ensure all IDs are the same in both dbs), you can do the same process just for the package, coreos_action and channels tables (assuming that you won't use CR to handle updates for any other app). That way you won't lose all your instances, events, activity, etc.

Something like this might work for the incremental updates:

On the exporting host:
```
pg_dump -U postgres coreroller -t package -t coreos_action -t channel --data-only > cr.sql
```

On the receiving one after copying the resulting file from the step above to it:
```
psql -U postgres coreroller -c 'DELETE FROM coreos_action; DELETE FROM package; DELETE FROM channel;'
psql -U postgres coreroller < cr.sql
```

Hope it helps. Will try to work on a better way of handling this soon.

Cheers.-

#5
