### ISSUE TITLE
CoreOS update check responds with error-instanceRegistrationFailed

### ISSUE THREAD

**Issue by jbw976** [coreroller/coreroller#15]
I'm seeing the following in the coreroller logs after building locally after pulling commit b7547e98ef1a513997ecb9997e590a8c1f476a31:
```
_t: 2016-06-08T00:41:40+0000 _p: 95 _n: omaha _l: DBG _m: Omaha trace XML: <request protocol="3.0" version="CoreOSUpdateEngine-0.1.0.0" ismachine="1" installsource="ondemandupdate" updaterversion="CoreOSUpdateEngine-0.1.0.0">
 <os platform="CoreOS" version="Chateau" sp="1058.3.0_x86_64"></os>
 <app appid="{e96281a6-d1af-4bde-9a0a-97b76e56dc57}" version="1058.3.0" lang="en-US" track="alpha" bootid="{bd94ffc3-c438-4bf7-a716-11398a39a92f}" machineid="f0ce3d10001f47e58a547b3df3e59885" oem="vagrant">
  <ping></ping>
  <updatecheck></updatecheck>
  <event eventtype="3" eventresult="2"></event>
 </app>
</request>
_t: 2016-06-08T00:41:40+0000 _p: 95 _n: omaha _l: INF _m: processEvent appID: {e96281a6-d1af-4bde-9a0a-97b76e56dc57} group: alpha event: 3.2 eventError:  previousVersion: 
_t: 2016-06-08T00:41:40+0000 _p: 95 _n: omaha _l: WRN _m: processEvent error: uuid: invalid UUID string: alpha
_t: 2016-06-08T00:41:40+0000 _p: 95 _n: omaha _l: DBG _m: Omaha trace XML: <response protocol="3.0" server="coreroller">
 <daystart elapsed_seconds="0"></daystart>
 <app appid="{e96281a6-d1af-4bde-9a0a-97b76e56dc57}" version="1058.3.0" status="error-instanceRegistrationFailed" track="alpha">
  <event status="ok"></event>
 </app>
</response>
```

It looks like the request's app track of "alpha" is not being resolved into its corresponding UUID.  This new code looks related:
https://github.com/coreroller/coreroller/commit/01bbd77ecd8a8e599ea4c0772522ab57d6aadf6c#diff-fc491ce1c513e797310e44e0051ebd99R79

Could it be because the request uses curly braces around the appid while coreosAppID in the code does not, causing the string comparison linked above to fail?

**Comment by tegioz** [comment]
Hi @jbw976

You are right, that comparison should support uuids with and without curly braces. I simplified (wrongly) that comparison when doing some refactoring a few days ago. I will fix it later today, thanks for reporting it!

**Comment by jbw976** [comment]
@tegioz, you guys are killing it with the quick turnaround bug fixes! thanks for the fantastic support!  I'll be happy to fix some in the future as well, more likely in the backend than the frontend :)

**Comment by tegioz** [comment]
Thanks @jbw976 , that'd be great :)
