### ISSUE TITLE
Web UI prompts for login multiple times for a single page load

### ISSUE THREAD

**Issue by jbw976** [coreroller/coreroller#17]
The web UI prompts to enter log in information fairly often when browsing, but it often prompts multiple times in a row for a single page load.  Perhaps asynchronous loading of page elements each trigger their own log in prompt?

I'm not much of a web dev, but I captured everything I thought may be useful from the Chrome dev tools, see all attached (both screenshots and log/txt files).

Also, Is the amount of time before log in expires configurable?  Thanks!

<img width="1680" alt="screen shot 2016-06-10 at 8 45 45 am" src="https://cloud.githubusercontent.com/assets/4313439/15970312/e16f7666-2ee8-11e6-9c5d-73559fc5e606.png">
<img width="1680" alt="screen shot 2016-06-10 at 8 45 58 am" src="https://cloud.githubusercontent.com/assets/4313439/15970311/e16dd482-2ee8-11e6-9fd0-03adbc1f5f1c.png">

[console-all.txt](https://github.com/coreroller/coreroller/files/309314/console-all.txt)
[console.txt](https://github.com/coreroller/coreroller/files/309315/console.txt)
[network.txt](https://github.com/coreroller/coreroller/files/309313/network.txt)

**Comment by tegioz** [comment]
Hi @jbw976

We've noticed this as well, it's mostly the result of letting the browser handling the basic http auth for us (as you mention multiple async requests are making it a bit worse). Initially the plan was to add a proper authentication system to CoreRoller using teams, roles, etc, but we didn't have much time so we added (temporarily) digest basic auth to have at least some auth in place in the meantime.

The 404 errors you get in the browser console are ok, the API is designed to return them when a particular resource is not found (it may happen when fetching the instances for a given app, for example) and the UI knows how to deal with them properly. So it's just a bit of noise in the console, no need to worry about it.

We'll think about this to check if there is something quick that can be done to improve the user experience. I've noticed that not all browsers show the authentication prompts so frequently as Chrome does (like Safari), so if it becomes very annoying a temporary solution may be to open the CR UI in a different browser.

Thanks!

**Comment by jbw976** [comment]
@tegioz, thank you for both the detailed explanation and potential workaround.  keep up the good work!

**Comment by TerraTech** [comment]
Any progress on this as I had to switch from Chrome to FireFox, however the login modal keeps popping up, though with FF it doesn't seem as frequent but still happens enough that its frustrating.

**Comment by TerraTech** [comment]
Looks good so far, no more auth nagging in FireFox or Chrome.

Thanks for fixing!
