### ISSUE TITLE
can't download updates from coreroller

### ISSUE THREAD

**Issue by lukasz-bielinski** [coreroller/coreroller#25]
hi, 

i run coreoroller 
docker run -d -p 8000:8000 -p 443:443 -p 80:80 coreroller/demo

and i added to exisiting coreos 
SERVER=http://192.168.1.103/v1/update/

but i see output from update_engine_client -update
LAST_CHECKED_TIME=0
PROGRESS=0.000000
CURRENT_OP=UPDATE_STATUS_CHECKING_FOR_UPDATE
NEW_VERSION=0.0.0.0
NEW_SIZE=0

and even from coreroller container i don't see open ports 80 neither 443. also this ports weren't mentioned in coreroller/backend{docker or kubernetes}

please advice how can update-engine connect to coreroller.

regards

**Comment by mimmus** [comment]
> from coreroller container i don't see open ports 80 neither 443. 
> also this ports weren't mentioned in coreroller/backend{docker or kubernetes}
> please advice how can update-engine connect to coreroller.

Same problem, any help?
