### ISSUE TITLE
Implement the omaha 'ping' action.

### ISSUE THREAD

**Issue by obiesmans** [coreroller/coreroller#26]
When a CoreOS update is applied but needs a reboot until it's active, update_engine will send pings. Coreroller does not update the instance`last_check_for_updates` in that case, causing the instance that haven't rebooted since `validityInterval` to be filtered out in most API queries.

**Comment by aquam8** [comment]
Hi,
This makes sense, i have added support for ping with commit f22e7a1 pushed to master. Your instance should not time out / be filteted out anymore.
Thank you for your ticket
