### ISSUE TITLE
Issue when trying to enable "office hours only" feature for an update group

### ISSUE THREAD

**Issue by xakraz** [coreroller/coreroller#30]
Hello,

I am facing an issue when I try to enable the "Office hours only" tick feature on an existing update group:

<img width="1680" alt="groupupdate_1" src="https://cloud.githubusercontent.com/assets/1590399/20113910/ab8f5e86-a5f2-11e6-8f00-da3df88e3013.png">
<img width="1680" alt="groupupdate_2" src="https://cloud.githubusercontent.com/assets/1590399/20113909/ab8f2966-a5f2-11e6-8b0e-e35bc326dd10.png">

Here are the logs of CoreRoller running in a docker container:

```
2016/11/08 19:31:38.345650 [05b8e44affe2/kXCwxmc8sC-000064] Started PUT "/api/apps/undefined/groups/5b810680-e36a-4879-b98a-4f989e80b899" from 172.17.0.1:46458
2016-11-08T19:31:38+0000 ERR rollerd updateGroup - updating group
   error: coreroller: expecting valid timezone
   group: map[application_id:undefined policy_timezone:Europe/Paris policy_update_timeout:30 minutes id:5b810680-e36a-4879-b98a-4f989e80b899 name:Alpha description:Tracks current development work and is released frequently channel_id:a87a03ad-4984-47a1-8dc4-3507bae91ee1 created_ts:0001-01-01T00:00:00Z rollout_in_progress:false policy_updates_enabled:true policy_safe_mode:true policy_period_interval:15 minutes instances_stats:map[complete:0 downloaded:0 onhold:0 undefined:0 update_granted:0 installed:0 downloading:0 total:0 error:0] policy_office_hours:true policy_max_updates_per_period:1]
2016/11/08 19:31:38.347213 [05b8e44affe2/kXCwxmc8sC-000064] Returning 400 in 1.529051ms
```

**Comment by tegioz** [comment]
Hi @xakraz 

Time zones information required to do the validation wasn't present on the container (tzdata package was missing). It should work fine now.

Thanks!

**Comment by xakraz** [comment]
Thank you for such a quick fix !
