### ISSUE TITLE
How to connect to the rollerd from the coreos server?

### ISSUE THREAD

**Issue by lalelunet** [coreroller/coreroller#34]
Hi,

I am running coreroller with the original dockerfiles. Everything is fine. 
The connection to IP:8000 in the browser is working. The updates from from coreos.com are added automatically to the db and are displayed in the web ui ...

The config from the server is modified to point to coreroller as mentioned in the readme.
server: https://your.coreroller.host/v1/update/ 
server: https://my.coreroller.host/v1/update/ 

In the log I can see that the updater try to connect to the coreroller host on port 443. This does not work because of the rollerd does not listen on this port.

> ...
> ...
> LastCheckedTime=0 Progress=0 CurrentOperation="UPDATE_STATUS_CHECKING_FOR_UPDATE" NewVersion=0.0.0.0 NewSize=0
> [0102/135605:INFO:libcurl_http_fetcher.cc(427)] Setting up timeout source: 1 seconds.
> [0102/135605:ERROR:libcurl_http_fetcher.cc(243)] Unable to get http response code: Failed to connect to my.coreroller.host port 443: Connection refused
> [0102/135605:INFO:libcurl_http_fetcher.cc(260)] No HTTP response, retry 1
> [0102/135615:INFO:libcurl_http_fetcher.cc(48)] Starting/Resuming transfer
> [0102/135615:INFO:libcurl_http_fetcher.cc(164)] Setting up curl options for HTTPS
> [0102/135615:INFO:libcurl_http_fetcher.cc(427)] Setting up timeout source: 1 seconds.
> [0102/135615:ERROR:libcurl_http_fetcher.cc(243)] Unable to get http response code: Failed to connect to my.coreroller.host port 443: Connection refused
> [0102/135615:INFO:libcurl_http_fetcher.cc(260)] No HTTP response, retry 2
> ...
> ...

Did I misunderstood somethings or what part I have overseen?

Thanks for your help

**Comment by tegioz** [comment]
Hi @lalelunet 

You can use the port CoreRoller is listening on (8000 in this case) in your url this way `http://your.coreroller.host:8000/v1/update/`.

Sergio.-

**Comment by lalelunet** [comment]
Hi Sergio,

thank you for your fast answer. This is working :)

Thomas
