### ISSUE TITLE
Stable channel automatically updated to a newer package

### ISSUE THREAD

**Issue by mimmus** [coreroller/coreroller#39]
I fixed 'stable' channel to 1235.12.0 but at 08:33am, 16/03 CoreOS published 1298.6.0 and stable channel was automatically updated to point to this release.
This is a BIG problem because we need to test every release before deploying updates to servers.

Can I safely block the channel to an older release?

**Comment by tegioz** [comment]
Hi @mimmus 

You can create your own groups and channels, so you are covered :) You can create a channel called `stable-verified` and point the stable group to it or even create a different group if that suits you better. Channels created by you won't be updated automatically so it's up to you to decide when to point it to a newer version.

Please note that when using your own groups (not stable, beta or alpha) you have to use the group id in your servers config, not the name. I think it's mentioned in the README, but just in case.

Sergio.-
