### ISSUE TITLE
Major update to coreos/go-omaha in progress

### ISSUE THREAD

**Issue by marineam** [coreroller/coreroller#43]
I'm starting work to greatly improve the somewhat crufty go-omaha package. The changes are an API break but in the end it should be easier to use. Additionally I'll be including generic server and client code to help make the behavior of update_engine and our own Core Update easier to understand.

My first pass which includes the refactor of the protocol structs and the addition of a simple server here: https://github.com/coreos/go-omaha/pull/18

Let me know if you have any feedback. Thanks!

**Comment by tegioz** [comment]
That sounds great @marineam, thanks for letting us know!
