### ISSUE TITLE
force rollerd to update CoreOS channels?

### ISSUE THREAD

**Issue by jaychris** [coreroller/coreroller#45]
Is there a way to force rollerd to update it's release channels, or enable debug so that I can see what's going on?  It's not clear how often it checks CoreOS for updates and the rollerd options don't show a debug option.  I just deployed postgres and rollerd (not the demo).  It's been deployed for over 3 hours so far and I don't see any attempts to update the channels, which still show the very old defaults.

I could try to add update.gz by hand, but I was hoping the auto-updater would remove the need to do so.  The host I'm running on has access to the internet...

**Comment by jaychris** [comment]
FWIW, the only thing in the log are these lines from the last 4 hours or so:

```
2017/05/08 18:19:02.801144 Starting Goji on [::]:8000
18:53:52.625583 WRN omaha processEvent error: coreroller: no update in progress
   in:
19:39:32.552293 WRN omaha processEvent error: coreroller: no update in progress
   in:
20:19:43.623595 WRN omaha processEvent error: coreroller: no update in progress
   in:
21:08:56.634086 WRN omaha processEvent error: coreroller: no update in progress
   in:
21:49:39.623792 WRN omaha processEvent error: coreroller: no update in progress
   in:
```

**Comment by tegioz** [comment]
Hi @jaychris 

You can't force rollerd to get new packages and/or update channels. It polls periodically the public CoreOS update servers (every hour) acting as any other CoreOS instance asking for updates, so it depends on the response received. Sometimes it may take a while to get them the first time, but eventually the latest packages for all channels will show up. You can certainly do it manually, but I'd recommend you to wait a bit.

`rollerd` uses [logxi](https://github.com/mgutz/logxi) for logging, so in your case to debug what the `syncer` component is doing you can run it this way:

`LOGXI=syncer=DBG ./rollerd`

Hope this helps.

Sergio.-
