### ISSUE TITLE
How do i get the latest version of the package

### ISSUE THREAD

**Issue by strahe** [coreroller/coreroller#47]
HI，
I want to upgrade the coreos system with coreroller,
but i found the latest version is always 829.0.0.
What should i do if i want to upgrade to the latest version?

**Comment by tegioz** [comment]
Hi @strahe 

New packages will be eventually added automatically by CoreRoller. Please see [CoreOS packages in CoreRoller](https://github.com/coreroller/coreroller#coreos-packages-in-coreroller) for more information about how it works.

Related issue: #45 

Sergio.-
