### ISSUE TITLE
Coreroller Load testing

### ISSUE THREAD

**Issue by shtihskar** [coreroller/coreroller#49]
Hi,

We are load testing coreroller at about 1000 update requests per minute. The bottle neck we are seeing is in DB response time. We see few SQL queries taking really long time:

```
2017-05-24 11:33:11 UTC:10.96.21.244(42896):coreroller@coreroller:[497]:LOG:  00000: duration: 2740.969 ms  statement: SELECT row_to_json(dat__item.*) FROM ( SELECT *, (SELECT array_agg(dat__version_breakdown.*) FROM (
		SELECT version, count(*) as instances, (count(*) * 100.0 / total) as percentage
		FROM instance_application, (
			SELECT count(*) as total 
			FROM instance_application 
			WHERE group_id=groups.id AND last_check_for_updates > now() at time zone 'utc' - interval '1 days'
			) totals
		WHERE group_id=groups.id AND last_check_for_updates > now() at time zone 'utc' - interval '1 days'
		GROUP BY version, total
		ORDER BY regexp_matches(version, '(\d+)\.(\d+)\.(\d+)')::int[] DESC
		) AS dat__version_breakdown) AS "version_breakdown", (SELECT row_to_json(dat__instances_stats.*) FROM (
		SELECT
			count(*) total,
			sum(case when status IS NULL then 1 else 0 end) undefined,
			sum(case when status = 3 then 1 else 0 end) error,
			sum(case when status = 2 then 1 else 0 end) update_granted,
			sum(case when status = 4 then 1 else 0 end) complete,
			sum(case when status = 5 then 1 else 0 end) installed,
			sum(case when status = 6 then 1 else 0 end) downloaded,
			sum(case when status = 7 then 1 else 0 end) downloading,
			sum(case when status = 8 then 1 else 0 end) onhold
		FROM instance_application
		WHERE group_id=groups.id AND last_check_for_updates > now() at time zone 'utc' - interval '1 days') AS dat__instances_stats) AS "instances_stats", (SELECT row_to_json(dat__channel.*) FROM (SELECT *, (SELECT row_to_json(dat__package.*) FROM (SELECT 
				package.*, 
				array_agg(pcb.channel_id) FILTER (WHERE pcb.channel_id IS NOT NULL) as channels_blacklist
			, (SELECT row_to_json(dat__coreos_action.*) FROM (SELECT * FROM coreos_action WHERE package_id = package.id) AS dat__coreos_action) AS "coreos_action" FROM package LEFT JOIN package_channel_blacklist pcb ON package.id = pcb.package_id WHERE (package.id = channel.package_id) GROUP BY package.id ORDER BY regexp_matches(version, '(\d+)\.(\d+)\.(\d+)')::int[] DESC) AS dat__package) AS "package" FROM channel WHERE (id = groups.channel_id) ORDER BY name ASC) AS dat__channel) AS "channel" FROM groups WHERE (id = '9a2deb70-37be-4026-853f-bfdd6b347bbe') ORDER BY created_ts DESC) as dat__item
```
This query takes about 2700ms when number of rows in instance table was about 19000, instance_status_history had about 39000 rows, event table had about 25000 rows.  The same query takes about 15-30ms when we delete the rows in DB. I guess some field is not being indexed.
We are running PostGre on AWS RDS on db.m4.xlarge

Thank you,
Rakshith

**Comment by tegioz** [comment]
Hi @shtihskar 

Wow that's a lot of instances! :-) 

Well, the truth is that we never anticipated such amount of instances in a single deployment and no optimisation has been done to the database so far so this is kind of expected. In fact, until two weeks ago the only indexes were the ones created automatically for the primary keys and unique constraints. Indexes for some foreign keys were added while preparing the 1.0 release.

Said that, I'm happy to take a look at it and see if we can improve the performance without incurring any major changes. Could you please provide a dump of the test database where you tested that query? 

Please note that the UI itself may not be ready to deal properly with such amount of instances. Pagination was never implemented in any section (still in the TODO list!), neither was a dedicated activity page with rich filtering support, so it may be hard to navigate it in your case.

Could you share a bit more about your use case (number of instances, applications you want to manage updates for -CoreOS only or others-, etc)? I feel curious about how CoreRoller is used out there :-) 

Sergio.-
