### ISSUE TITLE
Manually added CoreOS updates do not work

### ISSUE THREAD

**Issue by j-vizcaino** [coreroller/coreroller#5]
**Howto reproduce this:**

- goto CoreOS, add a new package (say for the stable channel)
- fill all the information (which seems to need the filename by the way, although the panel is not clear about this)
- set the new package as the new stable channel version
- try to update your CoreOS instance: the server replies with `status="internal-err"` and logs `error: coreroller: no update in progress`

Digging through the code, I found that the `coreos_action` for the package is never created! In your demo image, these are already created (presumably by `syncer` that calls `api.AddCoreosAction()`).

I find this rather disturbing because, when running Coreroller behind the firewall, I cannot use `syncer` to check for new updates, but want to add those manually.

Looking at the corresponding database table, adding a new CoreOS package would require the following fields to be specified:

- sha256 (calculated with `cat update.gz | openssl sha256 -binary | openssl base64`)
- is delta update (default to `false` until CoreOS supports delta updates)
- event (defaults to `postinstall` for now)

**Comment by tegioz** [comment]
Hi @j-vizcaino,

You are right, currently there isn't a proper way to add a CoreOS package through the UI. This was supposed to happen always through the syncer as you mention (it's a bit painful and error prone doing it manually though), but being behind a firewall is an expected use case so we need a better way of handling this. Being able to select the "CoreOS type" when creating a new package in the UI is misleading too.

As you have noticed looking at the code, CoreOS packages are a bit special and have some extra information that packages for other applications don't need at all (CoreRoller is used to handle updates for other applications as well, not just CoreOS).

In the meantime, the only solution is adding the packages manually to the database. This requires adding manually an entry to the package table and another to the coreos_action table. Some examples can be found in the api/db/migrations/0001_initial.sql file (which adds some default -old- initial packages).

Thanks for the tips about how to generate the hash. This wasn't documented (as requested in #4) because we've never done it manually before (the syncer has handled CoreOS packages management for us so far).

**Comment by j-vizcaino** [comment]
The ability to add a CoreOS package manually through the UI is indeed misleading. At least, a disclaimer  stating that '(WIP) CoreOS packages needs to be declared using syncer at the moment' would have saved me a lot a time.

I added manually the entries to the database but now `update-engine` cannot complete the update. I don't think this is related to coreroller though, but maybe because `coreos_procduction_update.bin.bz2` located in the download sections != `update.gz` served by the CoreOS update servers... I'll ask the CoreOS guys for hints.

Keep up the good work: Coreroller is on the way to becoming a nice product with a slick UI!
Thanks

**Comment by TerraTech** [comment]
Another use case is where we have to build a custom CoreOS image via the SDK to add some kernel modules that aren't available yet...  I currently have three open tickets regarding this...  In the meantime, we just wanted to add our built 'coreos_production_update.bin.gz' and ship them out to the cluster...  In this case, we are upgrading from 899.17.0 ==> 1010.5.0...

@j-vizcaino did you find out if it needed to be renamed to 'update.gz'

@tegioz can we use CoreRoller to push out our custom built image, or do we need to find another method?  We are using a custom 'CoreOS/FQ' group for our images...  So far, I haven't found any docs on how to manually update with a custom built image...  Everything I've read is to use CoreOS's offering, or use CoreRoller to push them out, but nothing for the manual case outside of just dd(ing) it into the USR-B partition and frobbing the GPT table...

**Comment by j-vizcaino** [comment]
@TerraTech Sadly, I did not investigate further on the expected update image format. I have a simpler method to update manually though. I'll be able to get it on monday.

**Comment by j-vizcaino** [comment]
@TerraTech Here is how I do manual updates:

```
wget http://url/xxx_update.bin.bz2
wget http://url/xxx_update.bin.bz2.sig
gpg --verify xxx_update.bin.bz2.sig
# Identify which part is the target: USR-A or USR-B
bunzip2 -c xxx_update.bin.bz2 > /dev/$target
mkdir /tmp/update
mount -o ro /dev/$target /tmp/update
/tmp/update/postinst /dev/$target
reboot
```

Hope this helps.

**Comment by TerraTech** [comment]
@j-vizcaino awesome, thank you for passing that along!  Your procedure looks much more streamlined then doing it then my manual nuts-n-bolts way...

**Comment by jbw976** [comment]
@j-vizcaino, @tegioz, @TerraTech

This particular issue is also relevant to our scenario where we are trying to use CoreRoller as an update server for our custom builds from our forked CoreOS sources.  First step here is just manually trying to get CoreRoller to successfully serve one of our updates to a CoreOS instance.

When trying to emulate the behavior of the syncer that populates the internal CoreRoller postgresql tables, I also discovered (like @j-vizcaino) that the update check will fail if there is no associated coreos_action for the package.

The syncer gets a full omaha response from the public/official CoreOS update server and then stashes relevant fields in postgresql.  Here's a real omaha response:
```
<response protocol="3.0" server="update.core-os.net">
 <daystart elapsed_seconds="0"></daystart>
 <app appid="e96281a6-d1af-4bde-9a0a-97b76e56dc57" status="ok">
  <updatecheck status="ok">
   <urls>
    <url codebase="https://update.release.core-os.net/amd64-usr/1053.2.0/"></url>
   </urls>
   <manifest version="1053.2.0">
    <packages>
     <package hash="sQXpFWTQtRWK14uLsGPLwK92zXo=" name="update.gz" size="240279887" required="false"></package>
    </packages>
    <actions>
     <action event="postinstall" ChromeOSVersion="" sha256="tSo32dLzLgJ+SwxcwMnVQvDZMzXUT2h2B0fra7q0gAQ=" needsadmin="false" IsDelta="false" DisablePayloadBackoff="true"></action>
    </actions>
   </manifest>
  </updatecheck>
 </app>
</response>
```
Note that the package has one hash and the postinstall event action has its own separate sha256 hash.  I assume  the package hash can be generated as @j-vizcaino suggested with `cat update.gz | openssl sha256 -binary | openssl base64`, but does anyone know how the sha256 of the postinstall event action is generated?  I could not determine how the update_engine uses/verifies this sha256 value: https://github.com/coreos/update_engine/blob/10adf687e9645e3dffa13b6eb886d5b1f038ac06/src/update_engine/omaha_request_action.cc#L515

The syncer just gets it from the official CoreOS update server, but for those that want to serve their own CoreOS builds with CoreRoller, it seems like we'd need to know how to generate this as well when adding our new package to CoreRoller.  Thanks!

**Comment by tegioz** [comment]
Hi,

Sorry about the late response. It looks like both fields can be generated from the `update.gz` file.

Hashes from the CoreRoller database for a given package (829.0.0, for example):
```
coreroller=# select hash from package where version='829.0.0';
2lhoUvvnoY359pi2FnaS/xsgtig=

coreroller=# select sha256 from coreos_action where package_id='284d295b-518f-4d67-999e-94968d0eed90';
1S9zQCLGjmefYnE/aFcpCjL1NsguHhQGj0UCm5f0M98=
```

Hashes generated them from the downloaded `update.gz` file for that version: 
```
wget https://commondatastorage.googleapis.com/update-storage.core-os.net/amd64-usr/829.0.0/update.gz

$ cat update.gz | openssl dgst -sha1 -binary | base64
2lhoUvvnoY359pi2FnaS/xsgtig=

$ cat update.gz | openssl dgst -sha256 -binary | base64
1S9zQCLGjmefYnE/aFcpCjL1NsguHhQGj0UCm5f0M98=
```

Hope this helps guys. I'll write some notes about this in the README.md as a reference.

Unfortunately I haven't tried a custom built image yet, but hopefully CoreRoller should be able to serve them just fine :) Please give it a try generating both hashes this way when you have some time and let me know if I can be of any help.

Cheers.-

**Comment by tegioz** [comment]
Hi,

It's possible now to manage CoreOS packages from the UI. A new field (CoreOS action sha256) has been added to the packages forms. Filling in that field triggers the creation of the corresponding coreos_action when needed (using the default values for the rest of the fields). Helper commands mentioned above to compute the hashes have been added below the corresponding fields as well.

Would love to hear if you have managed to serve custom built images to CoreOS instances from CoreRoller ;)

Sergio.-

**Comment by TerraTech** [comment]
@tegioz After coming up with a temporary workaround in #18 that fixed the omaha processing, I discovered that I made a terrible assumption as to what 'update.gz' actually is as served out by the official CoreOS rollers.

I had thought that I could build the core via the SDK, then do the following:

- gzip -c9 coreos_developer_update.bin > update.gz
- upload it to a nginx server with a URL I would add to CoreRoller
- update CoreRoller to my new release, hashes, and URL (1068.8.1)
- hoping for success (finally) but only to watch update-engine go up in flames

Digging through the logs, this jumped out at me:
`[0728/230429:ERROR:delta_performer.cc(274)] Bad payload format -- invalid delta magic.`

The magic string is: `CrAU`

Then I went and downloaded https://update.release.core-os.net/amd64-usr/1122.0.0/update.gz
took a look at it and saw the magic string at the beginning.  After digging further, I ended up at: https://www.chromium.org/chromium-os/chromiumos-design-docs/autoupdate-details

Which clearly shows the magic string and eventual manifest that is built.  So far, I have not figured out how to take a CoreOS image I've built and generate a valid `update.gz` file that update-engine can use.  I did find in the SDK a util called 'delta_generator' but I haven't figured out what options I need to use.  From the SDK docs, it appears that you push up the built image with `core_roller_upload` and behind the scenes at the remote side, their official roller processes do the magic.  Though I'm still not 100% sure this is the case, however looking at the SDK build system, I just haven't found if `update.gz` is handled locally or remotely.

At this point, all this is becoming more hassle than its worth, as release 1122.0.0 has included the kernel modules that I need, therefore I don't have to keep building custom updated CoreOS images and manually update my cluster.  But as with all great mysteries, I sure would love to know how to create a proper `update.gz` that update-engine can use in case I find myself having to build a new core via the SDK in the future.

I also like the idea of continuing to use CoreRoller internally, as I can control the deployment and rate limits on my end, without being a slave to the remote official rollers.

**Comment by tegioz** [comment]
Hi @TerraTech,

Unfortunately I can't be of much help as I've never tried to build a custom image yet (luckily). I'm sure you have learnt some quite interesting stuff while trying to make it work, so in the end these adventures are always worth it even if you don't fully succeed. And your findings may be a good starting point for others as well :)

About your last paragraph, for CoreOS we use it mostly for deployment control (dev/qa/prod with different groups/channels) as well, and the nice visibility the UI provides of your clusters (I don't think it's documented anywhere -it was some sort of experimental feature- but setting an environment variable you can also receive Hipchat notifications about important events in CoreRoller if that sounds interesting to you). But in addition to CoreOS, we deploy +20 applications/services using CoreRoller as well.

If for any reason I have to build a custom image in the future and I have more luck than you I'll let you know, I promise ;)

Thanks,
Sergio.-

**Comment by jbw976** [comment]
@TerraTech @tegioz 

We do custom CoreOS builds and I went through the exercise of figuring out how to properly generate the update.gz file.  The magic is performed by this script:
https://github.com/coreos/scripts/blob/master/core_sign_update

You can see a good example of this script being invoked here: https://github.com/coreos/scripts/blob/master/offline_signing/sign.sh#L15

One thing that really tripped me up was that the script takes *2* key pairs.  This is actually important, because the update_engine is hard coded to check the 2nd key pair.  It's an odd key versioning scheme really, so it doesn't matter what key you pass as the 1st one, the update_engine is hard coded to verify the second one.
https://github.com/coreos/update_engine/blob/master/src/update_engine/payload_signer.cc#L22
https://github.com/coreos/update_engine/blob/master/src/update_engine/payload_signer.cc#L242

Finally, you'll need to include the public key that you are signing the update with in your custom CoreOS image so the update engine has that key to verify the update payload with.  It's included in the following ebuild:
https://github.com/quantum/coreos-overlay/blob/master/coreos-base/coreos-au-key/coreos-au-key-0.0.4-r1.ebuild#L24

Hopefully that helps, took a fair amount of digging and help from the #coreos-dev guys (who are awesome, much like @tegioz) to figure it all out and get it working.

**Comment by tegioz** [comment]
This is great @jbw976, thanks!

**Comment by jbw976** [comment]
@TerraTech @tegioz 

i messed up the final link in my last post, and i'm not sure if ya'll get notifications for edits, so i wanted to call your attention the new/correct link to the public key getting included in the CoreOS image via ebuild.

last post is updated and again, this is the correct link:
https://github.com/coreos/coreos-overlay/blob/master/coreos-base/coreos-au-key/coreos-au-key-0.0.2.ebuild#L24

**Comment by TerraTech** [comment]
@jbw976 
UPDATE_STATUS_UPDATE_AVAILABLE ==> UPDATE_STATUS_DOWNLOADING ==> UPDATE_STATUS_FINALIZING ==> UPDATE_STATUS_FINALIZING ==> UPDATE_STATUS_UPDATED_NEED_REBOOT

The moment of truth was after a successful boot into my target: `1068.8.1+2016-07-29-0145`

That sequence of events is the rare relic obtained at the end of this crazy adventure.  Thank you so much for guiding me in the right direction as it was enough for me to divine the overall procedure to make CoreRoller plus custom built CoreOS images a reality.  I really can't thank you enough!

**Comment by jbw976** [comment]
@TerraTech @tegioz 

yessss! that is good news, i'm glad you got custom updates rolling.  with all the hard work of @tegioz @cynthia-sg etc. this project is looking pretty good.

looking forward to further updates and questions on this project, the community is healthy and i'm excited for new releases!

**Comment by aldivaca** [comment]
Hi! I'm running the demo Docker image all-in-one and I'm not seeing the latest packages of coreOS on the dashboard. I was reading through the docs and I didn't find if its any way I can force the update agains the CoreOS repos with syncer. Can anyone give me a hand with this? I test the docker container and it has connectivity to Internet. Thanks!!
