### ISSUE TITLE
unable to update...

### ISSUE THREAD

**Issue by vito21** [coreroller/coreroller#50]
Hey,

i´m testing stable version. im trying to update coreOS by hand from 1353.7.0 to  1353.8.0

/etc/coreos/update.conf
GROUP=stable
REBOOT_STRATEGY=etcd-lock
SERVER=http://rollerd.testing.cluster.XXXXXXXXX.de/v1/update/

journalctl -fu update-engine:

Jun 01 11:19:02 test-kublet-node3 update_engine[756]: I0601 11:19:02.026288   756 dbus_service.cc:57] Attempting interactive update
Jun 01 11:19:02 test-kublet-node3 update_engine[756]: I0601 11:19:02.026331   756 update_attempter.cc:263] New update check requested
Jun 01 11:19:02 test-kublet-node3 update_engine[756]: I0601 11:19:02.027791   756 omaha_request_params.cc:59] Current group set to stable
Jun 01 11:19:02 test-kublet-node3 update_engine[756]: I0601 11:19:02.027946   756 update_attempter.cc:483] Already updated boot flags. Skipping.
Jun 01 11:19:02 test-kublet-node3 update_engine[756]: I0601 11:19:02.027961   756 update_attempter.cc:626] Scheduling an action processor start.
Jun 01 11:19:02 test-kublet-node3 update_engine[756]: I0601 11:19:02.028069   756 action_processor.cc:36] ActionProcessor::StartProcessing: OmahaRequestAction
Jun 01 11:19:02 test-kublet-node3 update_engine[756]: I0601 11:19:02.028234   756 omaha_request_action.cc:245] Posting an Omaha request to http://rollerd.testing.cluster.xxxxxxxx.de/v1/update/
Jun 01 11:19:02 test-kublet-node3 update_engine[756]: I0601 11:19:02.028249   756 omaha_request_action.cc:246] Request: <?xml version="1.0" encoding="UTF-8"?>
Jun 01 11:19:02 test-kublet-node3 update_engine[756]: <request protocol="3.0" version="update_engine-0.4.2" updaterversion="update_engine-0.4.2" installsource="ondemandupdate" ismachine="1">
Jun 01 11:19:02 test-kublet-node3 update_engine[756]:     <os version="Chateau" platform="CoreOS" sp="1353.7.0_x86_64"></os>
Jun 01 11:19:02 test-kublet-node3 update_engine[756]:     <app appid="{e96281a6-d1af-4bde-9a0a-97b76e56dc57}" version="1353.7.0" track="stable" bootid="{247023de-9c0b-422f-b9fb-38cc907b6d20}" oem="" oemversion="" alephversion="1068.8.0" machineid="8bc99820bdb342e29a96e53fcfdcb233" lang="en-US" board="amd64-usr" hardware_class="" delta_okay="false" >
Jun 01 11:19:02 test-kublet-node3 update_engine[756]:         <ping active="1"></ping>
Jun 01 11:19:02 test-kublet-node3 update_engine[756]:         <updatecheck></updatecheck>
Jun 01 11:19:02 test-kublet-node3 update_engine[756]:         <event eventtype="3" eventresult="2" previousversion=""></event>
Jun 01 11:19:02 test-kublet-node3 update_engine[756]:     </app>
Jun 01 11:19:02 test-kublet-node3 update_engine[756]: </request>
Jun 01 11:19:02 test-kublet-node3 update_engine[756]: I0601 11:19:02.028260   756 libcurl_http_fetcher.cc:48] Starting/Resuming transfer
Jun 01 11:19:02 test-kublet-node3 update_engine[756]: I0601 11:19:02.028328   756 libcurl_http_fetcher.cc:152] Setting up curl options for HTTP
Jun 01 11:19:02 test-kublet-node3 update_engine[756]: I0601 11:19:02.029363   756 libcurl_http_fetcher.cc:427] Setting up timeout source: 1 seconds.
Jun 01 11:19:02 test-kublet-node3 update_engine[756]: I0601 11:19:02.049378   756 libcurl_http_fetcher.cc:240] HTTP response code: 200
Jun 01 11:19:02 test-kublet-node3 update_engine[756]: I0601 11:19:02.049479   756 libcurl_http_fetcher.cc:297] Transfer completed (200), 283 bytes downloaded
Jun 01 11:19:02 test-kublet-node3 update_engine[756]: I0601 11:19:02.049496   756 omaha_request_action.cc:592] Omaha request response: <response protocol="3.0" server="coreroller"><daystart elapsed_seconds="0"></daystart><app appid="{e96281a6-d1af-4bde-9a0a-97b76e56dc57}" version="1353.7.0" status="error-instanceRegistrationFailed" track="stable"><ping status="ok"></ping><event status="ok"></event></app></response>
Jun 01 11:19:02 test-kublet-node3 update_engine[756]: I0601 11:19:02.049631   756 omaha_request_action.cc:284] Nodeset is empty for /response/app/updatecheck
Jun 01 11:19:02 test-kublet-node3 update_engine[756]: I0601 11:19:02.049672   756 action_processor.cc:68] ActionProcessor::ActionComplete: OmahaRequestAction action failed. Aborting processing.
Jun 01 11:19:02 test-kublet-node3 update_engine[756]: I0601 11:19:02.049682   756 action_processor.cc:73] ActionProcessor::ActionComplete: finished last action of type OmahaRequestAction
Jun 01 11:19:02 test-kublet-node3 update_engine[756]: I0601 11:19:02.049690   756 update_attempter.cc:290] Processing Done.
Jun 01 11:19:02 test-kublet-node3 update_engine[756]: E0601 11:19:02.049710   756 update_attempter.cc:603] Update failed.
Jun 01 11:19:02 test-kublet-node3 update_engine[756]: I0601 11:19:02.049775   756 payload_state.cc:97] Updating payload state for error code: 34 (kActionCodeOmahaResponseInvalid)
Jun 01 11:19:02 test-kublet-node3 update_engine[756]: I0601 11:19:02.049790   756 payload_state.cc:103] Ignoring failures until we get a valid Omaha response.
Jun 01 11:19:02 test-kublet-node3 update_engine[756]: I0601 11:19:02.049901   756 action_processor.cc:36] ActionProcessor::StartProcessing: OmahaRequestAction
Jun 01 11:19:02 test-kublet-node3 update_engine[756]: I0601 11:19:02.049937   756 omaha_request_action.cc:245] Posting an Omaha request to http://rollerd.testing.cluster.XXXXXXX.de/v1/update/
Jun 01 11:19:02 test-kublet-node3 update_engine[756]: I0601 11:19:02.049947   756 omaha_request_action.cc:246] Request: <?xml version="1.0" encoding="UTF-8"?>
Jun 01 11:19:02 test-kublet-node3 update_engine[756]: <request protocol="3.0" version="update_engine-0.4.2" updaterversion="update_engine-0.4.2" installsource="ondemandupdate" ismachine="1">
Jun 01 11:19:02 test-kublet-node3 update_engine[756]:     <os version="Chateau" platform="CoreOS" sp="1353.7.0_x86_64"></os>
Jun 01 11:19:02 test-kublet-node3 update_engine[756]:     <app appid="{e96281a6-d1af-4bde-9a0a-97b76e56dc57}" version="1353.7.0" track="stable" bootid="{247023de-9c0b-422f-b9fb-38cc907b6d20}" oem="" oemversion="" alephversion="1068.8.0" machineid="8bc99820bdb342e29a96e53fcfdcb233" lang="en-US" board="amd64-usr" hardware_class="" delta_okay="false" >
Jun 01 11:19:02 test-kublet-node3 update_engine[756]:         <event eventtype="3" eventresult="0" errorcode="268435490"></event>
Jun 01 11:19:02 test-kublet-node3 update_engine[756]:     </app>
Jun 01 11:19:02 test-kublet-node3 update_engine[756]: </request>
Jun 01 11:19:02 test-kublet-node3 update_engine[756]: I0601 11:19:02.049957   756 libcurl_http_fetcher.cc:48] Starting/Resuming transfer
Jun 01 11:19:02 test-kublet-node3 update_engine[756]: I0601 11:19:02.049998   756 libcurl_http_fetcher.cc:152] Setting up curl options for HTTP
Jun 01 11:19:02 test-kublet-node3 update_engine[756]: I0601 11:19:02.051053   756 libcurl_http_fetcher.cc:427] Setting up timeout source: 1 seconds.
Jun 01 11:19:02 test-kublet-node3 update_engine[756]: I0601 11:19:02.057481   756 libcurl_http_fetcher.cc:240] HTTP response code: 200
Jun 01 11:19:02 test-kublet-node3 update_engine[756]: I0601 11:19:02.057595   756 libcurl_http_fetcher.cc:297] Transfer completed (200), 228 bytes downloaded
Jun 01 11:19:02 test-kublet-node3 update_engine[756]: I0601 11:19:02.057610   756 omaha_request_action.cc:592] Omaha request response: <response protocol="3.0" server="coreroller"><daystart elapsed_seconds="0"></daystart><app appid="{e96281a6-d1af-4bde-9a0a-97b76e56dc57}" version="1353.7.0" status="ok" track="stable"><event status="ok"></event></app></response>
Jun 01 11:19:02 test-kublet-node3 update_engine[756]: E0601 11:19:02.057626   756 omaha_request_action.cc:599] HTTP reported success but Omaha reports an error.
Jun 01 11:19:02 test-kublet-node3 update_engine[756]: I0601 11:19:02.057637   756 action_processor.cc:65] ActionProcessor::ActionComplete: finished last action of type OmahaRequestAction
Jun 01 11:19:02 test-kublet-node3 update_engine[756]: I0601 11:19:02.057644   756 action_processor.cc:73] ActionProcessor::ActionComplete: finished last action of type OmahaRequestAction
Jun 01 11:19:02 test-kublet-node3 update_engine[756]: I0601 11:19:02.057651   756 update_attempter.cc:290] Processing Done.
Jun 01 11:19:02 test-kublet-node3 update_engine[756]: I0601 11:19:02.057659   756 update_attempter.cc:294] Error event sent.

rollerd log:

{"_t":"2017-06-01T09:39:52+0000", "_p":"1", "_l":"ERR", "_n":"dat:sqlx", "_m":"exec.30", "err":"pq: invalid input syntax for type inet: \"10.20.96.193, 10.20.96.193\"", "_c":"/build/coreroller/backend/vendor/src/github.com/mgutz/logxi/v1/jsonFormatter.go:48 (0x5a025c)\n/build/coreroller/backend/vendor/src/github.com/mgutz/logxi/v1/jsonFormatter.go:61 (0x5a0469)\n/build/coreroller/backend/vendor/src/github.com/mgutz/logxi/v1/jsonFormatter.go:130 (0x5a1287)\n/build/coreroller/backend/vendor/src/github.com/mgutz/logxi/v1/jsonFormatter.go:177 (0x5a1ae7)\n/build/coreroller/backend/vendor/src/github.com/mgutz/logxi/v1/defaultLogger.go:117 (0x5990c2)\n/build/coreroller/backend/vendor/src/github.com/mgutz/logxi/v1/defaultLogger.go:94 (0x598dc8)\n/build/coreroller/backend/vendor/src/github.com/mgutz/logxi/v1/defaultLogger.go:102 (0x598eee)\n/build/coreroller/backend/vendor/src/gopkg.in/mgutz/dat.v1/sqlx-runner/exec.go:60 (0x68ceaa)\n/build/coreroller/backend/vendor/src/gopkg.in/mgutz/dat.v1/sqlx-runner/exec.go:99 (0x68e27f)\n/build/coreroller/backend/vendor/src/gopkg.in/mgutz/dat.v1/sqlx-runner/execer.go:39 (0x692df1)\n/build/coreroller/backend/src/api/instances.go:121 (0x55da95)\n/build/coreroller/backend/src/omaha/omaha.go:99 (0x56d799)\n/build/coreroller/backend/src/omaha/omaha.go:58 (0x56c7f2)\n/build/coreroller/backend/src/cmd/rollerd/controller.go:658 (0x414a65)\n/build/coreroller/backend/src/cmd/rollerd/rollerd.go:132 (0x4182b2)\n/build/coreroller/backend/vendor/src/github.com/zenazn/goji/web/handler.go:25 (0x57897e)\n/build/coreroller/backend/vendor/src/github.com/zenazn/goji/web/router.go:119 (0x57d107)\n/build/coreroller/backend/vendor/src/github.com/zenazn/goji/web/middleware.go:88 (0x57eb59)\n/usr/lib/go/src/net/http/server.go:1422 (0x50b5ca)\n/build/coreroller/backend/vendor/src/github.com/zenazn/goji/web/middleware/subrouter.go:42 (0x5a9cf7)\n\u003cautogenerated\u003e:2 (0x5abbcf)\n/build/coreroller/backend/vendor/src/github.com/zenazn/goji/web/middleware.go:50 (0x5792a6)\n/build/coreroller/backend/vendor/src/github.com/zenazn/goji/web/mux.go:53 (0x57a7c1)\n/build/coreroller/backend/vendor/src/github.com/zenazn/goji/web/router.go:119 (0x57d107)\n/build/coreroller/backend/vendor/src/github.com/zenazn/goji/web/middleware.go:88 (0x57eb59)\n/usr/lib/go/src/net/http/server.go:1422 (0x50b5ca)\n/build/coreroller/backend/vendor/src/github.com/zenazn/goji/web/middleware/options.go:70 (0x5aaa43)\n/usr/lib/go/src/net/http/server.go:1422 (0x50b5ca)\n/build/coreroller/backend/vendor/src/github.com/zenazn/goji/web/middleware/recoverer.go:29 (0x5aacda)\n/usr/lib/go/src/net/http/server.go:1422 (0x50b5ca)\n/build/coreroller/backend/vendor/src/github.com/zenazn/goji/web/middleware/request_id.go:68 (0x5ab174)\n/usr/lib/go/src/net/http/server.go:1422 (0x50b5ca)\n/build/coreroller/backend/vendor/src/github.com/zenazn/goji/web/middleware.go:46 (0x57920b)\n/build/coreroller/backend/vendor/src/github.com/zenazn/goji/web/mux.go:45 (0x57a70d)\n/usr/lib/go/src/net/http/server.go:1699 (0x50ce2d)\n/usr/lib/go/src/net/http/server.go:1862 (0x50d89e)\n/usr/lib/go/src/net/http/server.go:1361 (0x50b08e)\n/usr/lib/go/src/runtime/asm_amd64.s:1721 (0x4742a1)\n", "sql":"WITH upd AS ( UPDATE \"instance\" SET \"id\" = '8bc99820bdb342e29a96e53fcfdcb233', \"ip\" = '10.20.96.193, 10.20.96.193' WHERE (id = '8bc99820bdb342e29a96e53fcfdcb233') RETURNING \"id\",\"ip\"), ins AS ( INSERT INTO \"instance\"(\"id\",\"ip\") SELECT '8bc99820bdb342e29a96e53fcfdcb233','10.20.96.193, 10.20.96.193' WHERE NOT EXISTS (SELECT 1 FROM upd) RETURNING \"id\",\"ip\") SELECT * FROM ins UNION ALL SELECT * FROM upd", "args":"nil"}
{"_t":"2017-06-01T09:39:52+0000", "_p":"1", "_l":"ERR", "_n":"dat:sqlx", "_m":"exec.30", "err":"pq: invalid input syntax for type inet: \"10.20.96.193, 10.20.96.193\"", "_c":"/build/coreroller/backend/vendor/src/github.com/mgutz/logxi/v1/jsonFormatter.go:48 (0x5a025c)\n/build/coreroller/backend/vendor/src/github.com/mgutz/logxi/v1/jsonFormatter.go:61 (0x5a0469)\n/build/coreroller/backend/vendor/src/github.com/mgutz/logxi/v1/jsonFormatter.go:130 (0x5a1287)\n/build/coreroller/backend/vendor/src/github.com/mgutz/logxi/v1/jsonFormatter.go:177 (0x5a1ae7)\n/build/coreroller/backend/vendor/src/github.com/mgutz/logxi/v1/defaultLogger.go:117 (0x5990c2)\n/build/coreroller/backend/vendor/src/github.com/mgutz/logxi/v1/defaultLogger.go:94 (0x598dc8)\n/build/coreroller/backend/vendor/src/github.com/mgutz/logxi/v1/defaultLogger.go:102 (0x598eee)\n/build/coreroller/backend/vendor/src/gopkg.in/mgutz/dat.v1/sqlx-runner/exec.go:60 (0x68ceaa)\n/build/coreroller/backend/vendor/src/gopkg.in/mgutz/dat.v1/sqlx-runner/exec.go:99 (0x68e27f)\n/build/coreroller/backend/vendor/src/gopkg.in/mgutz/dat.v1/sqlx-runner/execer.go:39 (0x692df1)\n/build/coreroller/backend/src/api/instances.go:121 (0x55da95)\n/build/coreroller/backend/src/api/updates.go:57 (0x564f67)\n/build/coreroller/backend/src/omaha/omaha.go:107 (0x56da59)\n/build/coreroller/backend/src/omaha/omaha.go:58 (0x56c7f2)\n/build/coreroller/backend/src/cmd/rollerd/controller.go:658 (0x414a65)\n/build/coreroller/backend/src/cmd/rollerd/rollerd.go:132 (0x4182b2)\n/build/coreroller/backend/vendor/src/github.com/zenazn/goji/web/handler.go:25 (0x57897e)\n/build/coreroller/backend/vendor/src/github.com/zenazn/goji/web/router.go:119 (0x57d107)\n/build/coreroller/backend/vendor/src/github.com/zenazn/goji/web/middleware.go:88 (0x57eb59)\n/usr/lib/go/src/net/http/server.go:1422 (0x50b5ca)\n/build/coreroller/backend/vendor/src/github.com/zenazn/goji/web/middleware/subrouter.go:42 (0x5a9cf7)\n\u003cautogenerated\u003e:2 (0x5abbcf)\n/build/coreroller/backend/vendor/src/github.com/zenazn/goji/web/middleware.go:50 (0x5792a6)\n/build/coreroller/backend/vendor/src/github.com/zenazn/goji/web/mux.go:53 (0x57a7c1)\n/build/coreroller/backend/vendor/src/github.com/zenazn/goji/web/router.go:119 (0x57d107)\n/build/coreroller/backend/vendor/src/github.com/zenazn/goji/web/middleware.go:88 (0x57eb59)\n/usr/lib/go/src/net/http/server.go:1422 (0x50b5ca)\n/build/coreroller/backend/vendor/src/github.com/zenazn/goji/web/middleware/options.go:70 (0x5aaa43)\n/usr/lib/go/src/net/http/server.go:1422 (0x50b5ca)\n/build/coreroller/backend/vendor/src/github.com/zenazn/goji/web/middleware/recoverer.go:29 (0x5aacda)\n/usr/lib/go/src/net/http/server.go:1422 (0x50b5ca)\n/build/coreroller/backend/vendor/src/github.com/zenazn/goji/web/middleware/request_id.go:68 (0x5ab174)\n/usr/lib/go/src/net/http/server.go:1422 (0x50b5ca)\n/build/coreroller/backend/vendor/src/github.com/zenazn/goji/web/middleware.go:46 (0x57920b)\n/build/coreroller/backend/vendor/src/github.com/zenazn/goji/web/mux.go:45 (0x57a70d)\n/usr/lib/go/src/net/http/server.go:1699 (0x50ce2d)\n/usr/lib/go/src/net/http/server.go:1862 (0x50d89e)\n/usr/lib/go/src/net/http/server.go:1361 (0x50b08e)\n/usr/lib/go/src/runtime/asm_amd64.s:1721 (0x4742a1)\n", "sql":"WITH upd AS ( UPDATE \"instance\" SET \"id\" = '8bc99820bdb342e29a96e53fcfdcb233', \"ip\" = '10.20.96.193, 10.20.96.193' WHERE (id = '8bc99820bdb342e29a96e53fcfdcb233') RETURNING \"id\",\"ip\"), ins AS ( INSERT INTO \"instance\"(\"id\",\"ip\") SELECT '8bc99820bdb342e29a96e53fcfdcb233','10.20.96.193, 10.20.96.193' WHERE NOT EXISTS (SELECT 1 FROM upd) RETURNING \"id\",\"ip\") SELECT * FROM ins UNION ALL SELECT * FROM upd", "args":"nil"}

Could you point me in the right direction, what im doing wrong?

Thanks

**Comment by tegioz** [comment]
Hi @vito21 

The problem seems to be that the ip address value used ('10.20.96.193, 10.20.96.193') is not a valid `inet` value and the database complains.

The `ip` value is obtained from the `X-Forwarded-For` request header if present, falling back to the remote host address otherwise (you can see the code doing it [here](https://github.com/coreroller/coreroller/blob/5628145ae8c0a0ef4ce11c2900bc034d446f901f/backend/src/cmd/rollerd/controller.go#L666)). Maybe you can check if any proxy in your network is setting it that way. 

Sergio.-

**Comment by tegioz** [comment]
That `X-Forwarded-For` value is valid for that header though, so we'll definitely improve how it's parsed to handle cases like yours when multiple its are present.

Thanks!

**Comment by vito21** [comment]
Thanks for the quick replay!

The request goes as follows:

From node to external haproxy > from haproxy to ingress exposed rollerd service inside a other cluster.

Best!
