### ISSUE TITLE
beta/alpha channels updated, stable has nothing

### ISSUE THREAD

**Issue by schuylr** [coreroller/coreroller#52]
New installation, I noticed that rollerd pulled down the latest alpha/beta versions, but the stable channel has not been touched, nor do I see it under "Packages":

![screen shot 2017-06-01 at 5 28 24 pm](https://cloud.githubusercontent.com/assets/12628715/26701596/c0c12638-46ef-11e7-8665-4fdf0e708797.png)

It's been several hours with no further updates. Any tips?

**Comment by tegioz** [comment]
Hi @schuylr 

This is something expected the first time you get the packages for each channel. They'll show up eventually, nothing to worry about.

Please see [CoreOS packages in CoreRoller](https://github.com/coreroller/coreroller#coreos-packages-in-coreroller) for more information about how the packages are created (related issue: #45). 

Sergio.-

**Comment by schuylr** [comment]
Coming in today to see that now! Thanks for following up. I was mostly confused because I thought all three would update at once.

Excellent tool by the way, it's a lifesaver since the latest stable release has been killing my clusters. Kudos!
