### ISSUE TITLE
ssl certificate

### ISSUE THREAD

**Issue by lalelunet** [coreroller/coreroller#59]
Hi,

is there a option to run coreroller with a ssl certificate? I did not found information on how to use a certificate. In the README I found the URL setting with https and without.

SERVER=https://your.coreroller.host/v1/update/

I already run coreroller with your beta version instructions on port 8000. 

Thank you

**Comment by tegioz** [comment]
Hi @lalelunet 

CoreRoller itself doesn't support ssl, but there are a few ways you could set it up around it easily. You could extend the sample `rollerd` docker image, adding Nginx to act as a reverse proxy and let it handle the ssl termination. You could also add Nginx (Haproxy, etc) as a sidecar container and run both containers in the same pod. Or handle the ssl termination in a load balancer in your cloud provider if that's an option for you. Plenty of options :)

If would be easy to add support for it directly in CoreRoller though, I'll try to do it when I have some time.

Hope this helps,
Sergio.-
