### ISSUE TITLE
Disabling safe mode has no effect

### ISSUE THREAD

**Issue by j-vizcaino** [coreroller/coreroller#6]
**Howto reproduce this**

- disable safe mode for a CoreOS channel
- try to update your instance and make it fail (by using an improper URL in the package for example)
- after 2 attemps, the updates have been disabled

**Expected behavior**

- updates are still enabled

**Comment by tegioz** [comment]
Hi @j-vizcaino,

Thanks for your feedback, we'll address the problems you mention soon :)

"Safe mode" is meant to limit the amount of concurrent updates to one (regardless of the maximum updates you have defined in your rollout policy) until the first one has completed and succeeded. If it doesn't succeed, updates will be paused requiring human intervention to find out what went wrong. This can be useful to not deploy a broken package to multiple hosts simultaneously.

When not using "Safe mode", many instances (up to the maximum updates set in your rollout policy) can start processing an update simultaneously, but if the first one that completes doesn't succeed updates will be paused in that group too. The point of this mechanism is to stop the distribution of a package that didn't work for the first update attempt (suspicious package though), but at this point there might be more instances broken, thus not being fully safe at the expense of not delaying updates distribution (sometimes it's important to distribute updates quickly for some types of applications).

Unfortunately, this behaviour is not documented anywhere (we don't have many docs yet) and it can be confusing.

**Comment by j-vizcaino** [comment]
Thank you for clarifying this! I did not understand it properly. I can't remember exactly what the tooltip for the 'Safe mode' button says in the UI but maybe adding a bit of your explanation above in some sort of tooltip or help window would be a real plus.
