### ISSUE TITLE
Delete old hosts

### ISSUE THREAD

**Issue by ShaneSaww** [coreroller/coreroller#61]
I have hosts that are coming in and out, and it would be nice to delete a host from the UI.

**Comment by tegioz** [comment]
Hi @ShaneSaww 

The group view should only list instances that have requested an update in the last 24 hours, so old hosts should disappear eventually (from this view and from the application view). The goal was to avoid having to delete them manually in scenarios like the one you describe where instances are coming in and out all the time. Does this work for you?

**Comment by ShaneSaww** [comment]
The 24 hours thing is perfect! I didn't see that before!
Thanks!

**Comment by tegioz** [comment]
Cool, no worries :)
