### ISSUE TITLE
updateservicectl doesn't work with coreroller

### ISSUE THREAD

**Issue by odzhu** [coreroller/coreroller#64]
Hi Coreroller Team,

I'm trying to make **updateservicectl**  work with coreroller but seems doing something wrong:

```
updateservicectl -server=http://192.168.64.3:31300/v1/update/ app list
2017/08/02 15:57:29 googleapi: got HTTP response code 404 and error reading body: invalid character 'p' after top-level value
```
[My scenario](https://coreos.com/products/coreupdate/docs/latest/getting-started.html)

Providing user and key parameters gives same result also.

Any suggestion?

Thanks in advance.

**Comment by tegioz** [comment]
Hi @odzhu 

Unfortunately CoreRoller is not compatible with `updateservicectl`, as the exposed api is mostly different than CoreUpdate (except for the endpoint in charge of serving updates).

If you need to interact with CoreRoller programatically you can find some details in #46. There is also a feature request to implement a CLI in #44 (which would be the equivalent of `updateservicectl` for CoreRoller).

Sergio.-

**Comment by odzhu** [comment]
Thank you for clarificsation @tegioz
