### ISSUE TITLE
Support for cockroachdb

### ISSUE THREAD

**Issue by giepa** [coreroller/coreroller#65]
It would be great to be able to use our existing CockroachDB service instead of PostgreSQL. CockroachDB supports the PostgreSQL wire protocol, however it seems that Rollard uses some features specific to PostgreSQL.

**Comment by tegioz** [comment]
Hi @giepa 

I'm sorry but adding support for CockroachDB is out of the scope of this project. 

In addition to the features specific to PostgreSQL already used that you mention, it may make sense in the future to make use of some more for whatever reason. Not being able to do so feels a bit limiting. On top of that, trying to support both would add some extra overhead as any new feature, bug fix, PR, etc, would have to be written being aware of the PostgreSQL features supported by CockroachDB.

Thanks anyway for your suggestion.
