### ISSUE TITLE
Content type not set to `text/xml` on Omaha responses 

### ISSUE THREAD

**Issue by ShaneSaww** [coreroller/coreroller#68]
I noticed that when trying to get Omaha clients that use `https://github.com/coreos/go-omaha/tree/master/omaha/client` you will get responses back with errors due to the content type being set to `text/plain` not `text/xml`.  

It looks like doing a `w.Header().Set("Content-Type", "text/xml")` right before https://github.com/coreroller/coreroller/blob/master/backend/src/cmd/rollerd/controller.go#L659 will fix it. If you like I can submit a PR with that fix, but I'm unsure if that is the best solution.

**Comment by tegioz** [comment]
Hi @ShaneSaww 

Happy to accept a PR for this if it fixes that issue for you.
