### ISSUE TITLE
Ability to access CoreRoller in a path

### ISSUE THREAD

**Issue by RevREB** [coreroller/coreroller#70]
currently CoreRoller works just fine as the root path...
  http://www.coreroller.com:port/

But I have a need to deploy it via a nginx proxy at a path...
  https://www.proxy.com/coreroller/

now maybe im doing something wrong... but it just doesnt like to play nicely behind a proxy.

**Comment by mld** [comment]
You are not alone. Sadly (and unless something changed recently) there's only a workaround available, see #58 for details.

**Comment by RevREB** [comment]
closing this cause its hella old...
