### ISSUE TITLE
Can't override POSTGRESQLD_PORT_5432_TCP_ADDR with run --link

### ISSUE THREAD

**Issue by TerraTech** [coreroller/coreroller#9]
Greetings,

I'm not sure what I'm doing wrong (still learning), but I find that I cannot override this ENV via the --run --link switch
POSTGRESQLD_PORT_5432_TCP_ADDR=172.17.8.101 \

I am using both: coreroller/postgres and coreroller/rollerd

$ docker run -d -p 8000:8000 --link coreroller-postgres:postgresqld --name coreroller-rollerd  coreroller/rollerd

This won't start because the coreroller/postgres container's IP address is: 172.17.0.7

Running it with:  env
COREROLLER_DB_URL=postgres://postgres@172.17.8.101:5432/coreroller?sslmode=disable
COREROLLER_DIR=/coreroller
DEBIAN_FRONTEND=noninteractive
GOLANG_DOWNLOAD_SHA256=6d894da8b4ad3f7f6c295db0d73ccc3646bce630e1c43e662a0120681d47e988
GOLANG_DOWNLOAD_URL=https://golang.org/dl/go1.6.1.linux-amd64.tar.gz
GOLANG_VERSION=1.6.1
GOPATH=/go
HOME=/root
HOSTNAME=7b4a302e358d
LANG=en_US.UTF-8
LANGUAGE=en_US.UTF-8
PATH=/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
POSTGRESQLD_ENV_GOSU_VERSION=1.7
POSTGRESQLD_ENV_LANG=en_US.utf8
POSTGRESQLD_ENV_PGDATA=/var/lib/postgresql/data
POSTGRESQLD_ENV_PG_MAJOR=9.4
POSTGRESQLD_ENV_PG_VERSION=9.4.7-1.pgdg80+1
POSTGRESQLD_NAME=/coreroller-rollerd/postgresqld
POSTGRESQLD_PORT=tcp://172.17.0.7:5432
POSTGRESQLD_PORT_5432_TCP=tcp://172.17.0.7:5432
POSTGRESQLD_PORT_5432_TCP_ADDR=172.17.8.101
POSTGRESQLD_PORT_5432_TCP_PORT=5432
POSTGRESQLD_PORT_5432_TCP_PROTO=tcp
TERM=xterm

I have found that I can override by explicitly passing '--env POSTGRESQLD_PORT_5432_TCP_ADDR=172.17.0.7'

My google foo has failed me, and I don't know if '--link' is able to override an ENV variable like passing in '--env' can...

As an aside, why is the IP address '172.17.8.101' hardwired in (if --link cannot override)?

Thank you for any assistance you can provide!

**Comment by tegioz** [comment]
Hi @TerraTech 

You weren't doing anything wrong, the POSTGRESQLD* environment vars shouldn't be being set in the rollerd Dockerfile. It should be fixed now. COREROLLER_DB_URL is using now "postgresqld" as hostname, which should be added to /etc/hosts when linking rollerd container to the postgresql one, but feel free to pass a custom COREROLLER_DB_URL environment variable to the container to modify this behaviour (if needed).

Thank you very much for reporting this! :)
